// frontend/src/app/not-found/not-found.component.ts
import { Component, OnInit } from '@angular/core';

import { AppHeaderComponent } from '../app-header/app-header.component'
import { AppFooterComponent } from '../app-footer/app-footer.component'


@Component({
  selector: 'not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.scss']
})
export class NotFoundComponent implements OnInit {

  ngOnInit() {
  }

}

// frontendv2/src/components/not-found.vue
<template src="./not-found.html"></template>
<style lang="scss" src="./not-found.scss"></style>

<script lang="ts">
import { Vue, Component, Prop, Mixins } from "vue-property-decorator"

import AppHeader from '../components/app-header.vue'
import AppFooter from '../components/app-footer.vue'

@Component({
    components: { AppHeader, AppFooter }
})
export default class Domains extends Vue {

}
</script>
