// dev/front/src/app/not-found/not-found.component.ts
import { Component } from '@angular/core';
import { fadeAnimation } from '../app.animations'

@Component({
  selector: 'not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.scss'],
    animations: [ fadeAnimation ]
})
export class NotFoundComponent {

}

<div>
    <app-header></app-header>



    <app-footer></app-footer>
</div>

// frontendv2/src/components/not-found.vue
<template src="./not-found.html"></template>
<style lang="scss" src="./not-found.scss"></style>

<script lang="ts">
import { Vue, Component, Prop, Mixins } from "vue-property-decorator"

import AppHeader from '../components/app-header.vue'
import AppFooter from '../components/app-footer.vue'

@Component({
    components: { AppHeader, AppFooter }
})
export default class Domains extends Vue {

}
</script>
