// frontend/src/app/login/login.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core'
import { FormGroup, FormControl, FormBuilder, Validators } from '@angular/forms'
import { HttpClient } from '@angular/common/http'

import { LoginService } from '../login.service'

@Component({
    selector: 'login',
    templateUrl: './login.component.html',
    styleUrls: [ './login.component.scss' ]
})
export class LoginComponent implements OnInit {

    loginForm: FormGroup
    message: string = ''
    attemptCount: number = 0

    constructor(
        private formBuilder: FormBuilder,
        private loginService: LoginService
    ) {}

    login(event) {
        if (this.loginService.login(event.value.name, event.value.password)) {
            this.message = `Wow! Login successful`
            return
        }
        setTimeout(() => {
            this.attemptCount++
            this.message = `Login incorrect. Attempt ${this.attemptCount}`
        }, 1000 )

    }

    ngOnInit() {
        this.loginForm = this.formBuilder.group({
            name: [ 'qwerty' ],
            password: [ '12345' ]
        })
    }
}

<div>

    <div class="top-bar">
        <div class="top-bar-left padding-left-2">
            <ul class="menu">
                <li class="menu-text"><i class="fi-shield" style="font-size: 1.3em;"></i></li>
                <li class="menu-text">Login</li>
            </ul>
        </div>
    </div>


    <div class="grid-container">
        <div class="grid-x grid-padding-x align-center">
            <div class="cell small-8 medium-4 large-3">

                <div class="card padding-2 margin-top-3">

                    <form accept-charset="UTF-8" [formGroup]="loginForm" (ngSubmit)="login(loginForm)">
                        <label>Login name (qwerty)
                            <input type="text" formControlName="name">
                        </label>
                        <label>Password (12345)
                            <input type="password" formControlName="password">
                        </label>
                        <div class="text-center">
                            <button class="button small" type="submit">Submit</button>
                        </div>
                    </form>

                    <div class="margin-2">
                        <div class="text-center">
                            {{ message }}
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>

// frontend/src/Login.vue
<template>
    <div>

        <div class="grid-container margin-top-2">
            <div class="grid-x grid-padding-x align-center">
                <div class="cell small-8 medium-4 large-3">

                    <div class="card padding-1">
                        <form accept-charset="UTF-8" v-on:submit.prevent="submitLogin()">

                            <label>Login (qwerty@sample.org)
                                <input type="text" v-model.trim="loginName" placeholder="login">
                            </label>

                            <label>Password (12345)
                                <input type="password" v-model.trim="password" placeholder="password">
                            </label>

                            <div class="text-center">
                                <button class="button small" type="submit">Send</button>
                            </div>
                            <p class="text-center">
                                {{ message }}
                            </p>
                        </form>
                    </div>

                    <pre>{{ debug }}</pre>

                </div>
            </div>
        </div>

    </div>
</template>

<script lang="ts">

import { Vue, Component, Prop, Watch } from "vue-property-decorator"
import { State, Action, Getter, Mutation } from 'vuex-class'


@Component
export default class Login extends Vue {

    loginName : string = ''
    password : string = ''
    message : string = ''
    debug : any = ''

    @Getter isAuth: boolean
    @Action setLogin: () => void

    submitLogin() {
        

    }

    mounted() {
    }

}
</script>
